version: "3"

services:
  web:
    build: ./web
    command: python app.py
    volumes:
      - ./web/src:/code
    ports:
      - "5000:5000"

  mqtt: # docker run --name mqtt --restart=always -tid -p 1883:1883 -p 9001:9001 toke/mosquitto
    image: toke/mosquitto
    ports:
      - "1883:1883" # standard
      - "9001:9001" # websockets

  testpaho:
    build: ./test-paho
    command: python app.py
    volumes:
      - ./test-paho/src:/code
    restart: always
