version: "3"

services:
  web:
    build: ./web
    volumes:
      - ./web/src:/code
    command: ["python", "app.py"]
    ports:
      - "5000:5000"

  mqtt: # docker run --name mqtt --restart=always -tid -p 1883:1883 -p 9001:9001 toke/mosquitto
    # image: toke/mosquitto
    build: ./mqtt
    volumes:
      - ./mqtt/mosquitto/data:/mosquitto/data
      - ./mqtt/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883" # standard
      - "9001:9001" # websockets

  testpaho:
    build: ./test-paho
    command: ["python", "app.py"]
    volumes:
      - ./test-paho/src:/code
    depends_on:
      - "mqtt" # https://docs.docker.com/compose/startup-order/
